package main

import (
	"testing"

	"github.com/shadesfear/aoc-lib-go/files"
)

func TestPart1(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	expected := 14
	lines := files.StringToLines(input)
	res := solvePart1(lines)

	if expected != res {
		t.Errorf("Expected %d, got %d", expected, res)
	}
}

func TestPart2(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

	expected := 34
	lines := files.StringToLines(input)
	res := solvePart2(lines)

	if expected != res {
		t.Errorf("Expected %d, got %d", expected, res)
	}
}
